export const CATEGORIES = [
  {
    id: 'cards',
    name: 'Cards Expiry',
    icon: 'credit-card',
    color: '#E53935',
    fields: [
      { key: 'cardName', label: 'Card Name', type: 'text', required: true },
      { key: 'bank', label: 'Bank / Issuer', type: 'text', required: true },
      { key: 'lastFour', label: 'Last 4 Digits', type: 'number' },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date', required: true },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'expiryDate',
  },
  {
    id: 'lic',
    name: 'LIC Payments',
    icon: 'shield-account',
    color: '#8E24AA',
    fields: [
      { key: 'policyName', label: 'Policy Name', type: 'text', required: true },
      { key: 'policyNo', label: 'Policy Number', type: 'text', required: true },
      { key: 'premium', label: 'Premium Amount (₹)', type: 'number', required: true },
      { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
      { key: 'frequency', label: 'Frequency', type: 'select', options: ['Monthly', 'Quarterly', 'Half-Yearly', 'Yearly'] },
      { key: 'maturityDate', label: 'Maturity Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'dueDate',
  },
  {
    id: 'medical',
    name: 'Medical Insurance',
    icon: 'hospital-box',
    color: '#00897B',
    fields: [
      { key: 'provider', label: 'Insurance Provider', type: 'text', required: true },
      { key: 'policyNo', label: 'Policy Number', type: 'text', required: true },
      { key: 'sumInsured', label: 'Sum Insured (₹)', type: 'number' },
      { key: 'premium', label: 'Premium Amount (₹)', type: 'number' },
      { key: 'renewalDate', label: 'Renewal Date', type: 'date', required: true },
      { key: 'members', label: 'Members Covered', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'renewalDate',
  },
  {
    id: 'antivirus',
    name: 'Antivirus',
    icon: 'shield-check',
    color: '#1E88E5',
    fields: [
      { key: 'software', label: 'Software Name', type: 'text', required: true },
      { key: 'device', label: 'Device / License For', type: 'text', required: true },
      { key: 'licenseKey', label: 'License Key', type: 'text' },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date', required: true },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'expiryDate',
  },
  {
    id: 'pollution',
    name: 'Pollution Certificate',
    icon: 'leaf',
    color: '#43A047',
    fields: [
      { key: 'vehicleNo', label: 'Vehicle Number', type: 'text', required: true },
      { key: 'vehicleType', label: 'Vehicle Type', type: 'select', options: ['Car', 'Bike', 'Truck', 'Auto', 'Other'] },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date', required: true },
      { key: 'center', label: 'PUC Center', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'expiryDate',
  },
  {
    id: 'vehicle_insurance',
    name: 'Vehicle Insurance',
    icon: 'car',
    color: '#FB8C00',
    fields: [
      { key: 'vehicleNo', label: 'Vehicle Number', type: 'text', required: true },
      { key: 'vehicleType', label: 'Vehicle Type', type: 'select', options: ['Car', 'Bike', 'Truck', 'Auto', 'Other'] },
      { key: 'provider', label: 'Insurance Provider', type: 'text', required: true },
      { key: 'policyNo', label: 'Policy Number', type: 'text' },
      { key: 'premium', label: 'Premium Amount (₹)', type: 'number' },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date', required: true },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'expiryDate',
  },
  {
    id: 'ppf',
    name: 'PPF Payments',
    icon: 'bank',
    color: '#6D4C41',
    fields: [
      { key: 'accountNo', label: 'Account Number', type: 'text', required: true },
      { key: 'bank', label: 'Bank / Post Office', type: 'text', required: true },
      { key: 'depositAmount', label: 'Deposit Amount (₹)', type: 'number', required: true },
      { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
      { key: 'frequency', label: 'Frequency', type: 'select', options: ['Monthly', 'Quarterly', 'Yearly'] },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'dueDate',
  },
  {
    id: 'ssy',
    name: 'SSY Payments',
    icon: 'account-child',
    color: '#F06292',
    fields: [
      { key: 'accountNo', label: 'Account Number', type: 'text', required: true },
      { key: 'bank', label: 'Bank / Post Office', type: 'text', required: true },
      { key: 'depositAmount', label: 'Deposit Amount (₹)', type: 'number', required: true },
      { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
      { key: 'beneficiary', label: "Beneficiary (Daughter's Name)", type: 'text' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'dueDate',
  },
  {
    id: 'mobile',
    name: 'Mobile Plans',
    icon: 'cellphone',
    color: '#039BE5',
    fields: [
      { key: 'operator', label: 'Operator', type: 'select', options: ['Jio', 'Airtel', 'Vi', 'BSNL', 'Other'] },
      { key: 'number', label: 'Mobile Number', type: 'number', required: true },
      { key: 'planName', label: 'Plan Name / Amount (₹)', type: 'text', required: true },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date', required: true },
      { key: 'data', label: 'Daily Data', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'expiryDate',
  },
  {
    id: 'custom',
    name: 'Custom',
    icon: 'plus-circle',
    color: '#546E7A',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'dueDate', label: 'Due Date', type: 'date', required: true },
      { key: 'amount', label: 'Amount (₹)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'text' },
    ],
    dateField: 'dueDate',
  },
];

export const getCategoryById = (id) => CATEGORIES.find((c) => c.id === id);
